version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./example:/code/example/
      - ./allauth:/code/allauth
      - ./db:/srv/db
    env_file:
      - .env
    environment:
      DATABASE_NAME: /srv/db/example.db
    ports:
      - $AUTH_PORT:$AUTH_PORT
    command:
      - make
      - migrate
      - makeadmin
      - runserver
